name: Update Dev Metrics

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      API_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
      STATS_URL: ${{ vars.STATS_URL }}
      SECTION_NAME: DEV_METRICS
      COMMIT_MESSAGE: Updated with Dev Metrics
      SYMBOL_VERSION: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node scripts/generate-dev-metrics.js

      - run: |
          git config --global user.name "readme-bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md commit-history.svg
          git commit -m "$COMMIT_MESSAGE" || echo "No changes"
          git push
